movieweb_app/blueprints/movies.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user

from movieweb_app import db
from movieweb_app.data_manager.sqltie_data_manager import SQLiteDataManager
from movieweb_app.models import UserMovie, Movie
from movieweb_app.movie_api_manager.movie_data_fetcher import MovieDataFetcher

# Movies Blueprint
movies_bp = Blueprint('movies', __name__, template_folder='templates', static_folder='static',
                      static_url_path='users_manager/static', url_prefix='/users/account/')

# Creating a data_db manager object
data_manager = SQLiteDataManager()

# Creates instance the movie data_db fetcher object that fetches movies data_db from IMDb movies api
movies_data = MovieDataFetcher()

def new_movie_id():
    """
    Generates a new id for new movie object. Returns the value of the id as int.
    :return: int
    """
    return max([movie.id for movie in data_manager.all_movies]) + 1

def get_movies_data(movie_name):
    """
    Gets a movie name as parameter and returns a movie object
    :param movie_name: string
    :return: Movie Object OR None
    """
    # Get movie data_db from imdb movie api
    movie_data = movies_data.get_movies_data(movie_name)

    if movie_data:
        try:
            new_movie_data = Movie(
                title=movie_data['Title'],
                genre=movie_data['Genre'],
                year=movie_data['Year'],
                rating=movie_data['imdbRating'],
                country=movie_data['Country'],
                cover_url=movie_data['Poster'],
                plot=movie_data['Plot'],
                actors=movie_data['Actors'],
                trailer_id=movie_data['imdbID'],
                award=movie_data['Awards'],
                id=new_movie_id(),
                user_id=current_user.id
            )
            return new_movie_data
        except KeyError:
            pass
    return None


@movies_bp.route('<int:user_id>/add_movie', methods=['GET', 'POST'])
@login_required
def add_movie(user_id):
    """
    Route for adding new movies to user's list
    :param user_id: int
    """

    # Gets user instance from the User table
    user = data_manager.get_user_by_id(user_id)
    user_movies = data_manager.get_user_movies(user_id)

    # Handles GET request and displays the add movie form to the user
    if request.method == 'GET':
        return render_template('movies_manager.html', user_movies=user_movies, current_user=current_user)

    # Gets movie_name from the form
    movie_name = request.form.get('movie_name')

    # Gets the new_movie instance (e.g new_movie = Movie(title=tile, rating=rating, ...))
    new_movie_data = get_movies_data(movie_name)

    if new_movie_data:
        # Checks if movie already in the movies table. Just to avoid multiple users adding same movie
        movie_exists = data_manager.get_movie_by_title(new_movie_data.title)

        if movie_exists:
            # Query the UserMovies table to see if the movie is already associated to the user
            # so that a user don't add the same movie that is already in the user's movie list
            user_movie_exists = data_manager.get_movie_from_user_movie_list(user.id, movie_exists.id)
            if user_movie_exists:
                flash(f'The {movie_name} already exists in your favourite movie list add another movie', 'success')

                # Redirect user to user_movies route to  display the list of user's movies
                return redirect(url_for('users.user_movies', user_id=user_id))

            # If a move has been added to the movies table perhaps by another user, then no need to duplicate the
            # movie, just create a relationship between the current user andthe existing movie.
            # Save the user-movie association to the UserMovie table
            user_movie = UserMovie(user=user, movie=movie_exists)

            db.session.add(user_movie)
            db.session.commit()
            flash(f'The {movie_name} has been add to your favourite movie list', 'success')

            # Redirect user to user_movies route to  display the list of user's movies
            return redirect(url_for('users.user_movies', user_id=user_id))

        print(new_movie_data)
        # If its a new movie, then add movie to the Movie Table
        db.session.add(new_movie_data)
        db.session.commit()

        # Create the relationship between the user and new movie in the UserMovie table
        user_movie = UserMovie(user=user, movie=new_movie_data)

        # Save user-movies association to the UserMovie table
        db.session.add(user_movie)
        db.session.commit()

        flash(f'The {movie_name} has been add to your favourite movie list', 'success')

        # Redirect user to user_movies route to  display the list of user's movies
        return redirect(url_for('users.user_movies', user_id=user_id))

    # Else return an error message, movie not found!
    flash(f'The {movie_name} was not found', 'error')

    # Redirect user to user_movies route to  display the list of user's movies
    return render_template('movies_manager.html', user_movies=user_movies, current_user=current_user)


@movies_bp.route('<int:user_id>/update_movie/<int:movie_id>', methods=['GET', 'POST'])
@login_required
def update_movie(user_id, movie_id):
    """
    Route for updating details of a specific movie in a user's movies list
    :param user_id: int
    :param movie_id: int
    """

    # Gets the user-movie object (e.g user_movie = UserMovie(user_id, movie_id))
    # The user_movie object has a reference to both the User and Movie model using the db.backref() function
    user_movie = data_manager.get_movie_from_user_movie_list(user_id, movie_id)

    if request.method == 'GET':
        # Handle GET request and render the update movie html
        return render_template('update_movie.html', user_id=user_id, user_movie=user_movie.movie)

    # Access and update movie properties in movies table through the user_movie instance
    if user_movie:
        user_movie.movie.actors = request.form.get('movie_actors')
        user_movie.movie.genre = request.form.get('movie_genre')
        user_movie.movie.plot = request.form.get('movie_plot')

        # Commit the changes to the database
        db.session.commit()

        flash(f'{user_movie.movie.title} has been updated successfully', 'success')
    else:
        flash(f' The {user_movie.movie.title} is not found in your list of movies', 'success')

        # Redirect user to user_movies route to  display the list of user's movies
        return render_template('movies_manager.html', user_movies=data_manager.get_user_movies(user_id),
                               current_user=current_user)

    # Redirects user to the user movie list page
    return redirect(url_for('users.user_movies', user_id=user_id))


@movies_bp.route('<int:user_id>/delete_movie/<int:movie_id>', methods=['POST'])
@login_required
def delete_movie(user_id, movie_id):
    """
    Route for deleting a specific movie from a user's list
    :param user_id: int
    :param movie_id: int
    """

    # Get movie to delete
    movie_to_delete = data_manager.get_movie_by_id(movie_id)
    user_movie = data_manager.get_movie_from_user_movie_list(user_id, movie_id)

    if user_movie:
        # Delete User Movie Association (or Relation)
        db.session.delete(user_movie)
        db.session.commit()

        flash(f'{movie_to_delete.title} has been deleted successfully', 'success')
    else:
        flash(f' The {movie_to_delete.title} is not found in your list of movies', 'success')

    # Redirects user to the user movie list page
    return redirect(url_for('users.user_movies', user_id=user_id))


# This route has not been implemented due to time constriants. Will be implemented later on.
@movies_bp.route('<int:user_id>/watched_movie/<int:movie_id>/<string:watched_status>', methods=['POST'])
@login_required
def watched_movie(user_id, movie_id, watched_status):
    """
    Checks and updates the watch status of a specific movie in a user's movies list
    :param user_id: int
    :param movie_id: int
    :param watched_status: string ("YES" or "NO")
    """

    # Fetch user movies
    user_movie = data_manager.get_movie_from_user_movie_list(user_id, movie_id)

    if user_movie:
        if watched_status.lower() == 'no':
            user_movie.watch_status = 'Yes'
            db.session.commit()
        else:
            user_movie.watch_status = 'No'
            db.session.commit()

    # Redirects user to the movies manager page
    return redirect(url_for('movies.add_movie', user_id=user_id))

movieweb_app/blueprints/users.py
from datetime import datetime
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user

from movieweb_app import bcrypt, db
from movieweb_app.blueprints.user_auth import SignupForm, SigninForm
from movieweb_app.data_manager.sqltie_data_manager import SQLiteDataManager
from movieweb_app.models import User
from movieweb_app.movie_api_manager.movies_info import MoviesInfo

# Initializing the Blueprint object
users_bp = Blueprint('users', __name__, template_folder='templates', static_folder='static',
                     static_url_path='users_manager/static', url_prefix='/users')


# Initializing the data_db manager object
data_manager = SQLiteDataManager()

def serialize_user_data():
    """
    serializes the data for HTML templating
    :return: user_data: list[dict]
    """
    users_data = []
    users = data_manager.all_users

    for user in users:

        # Gets all the movies of each user. Each movie is a movie object
        user_movies = data_manager.get_user_movies(user.id)

        # Initializing the data_db manager object
        movies_info = MoviesInfo(user_movies)

        serialized_user = {
            "id": user.id,
            "name": user.name,
            "username": user.username,
            "likes": user.like_count,
            "date": user.date_registered,
            "favourite_movies": movies_info.total_favourite_movies,
            "highly_rated": movies_info.high_rated_movies,
            "recent_movies": movies_info.recent_movie_release,
            "movies_watched": movies_info.total_movies_watched,
            "worst_rating": movies_info.worst_movie_rating,
            "movie_awards": movies_info.total_movies_with_award,
            "most_movies_countries": movies_info.movies_count_by_countries,
            "top_rated_movie_name": movies_info.top_rated_movie_name,
            "movies": user_movies # movie objects
        }

        users_data.append(serialized_user)
    return users_data


def get_current_user_info(current_user_id):
    """
    Gets the id of the current user and returns a user_data as dictionary
    :param current_user_id: int(logged in user id)
    :return: dict(id:user_id, name: username, ...)
    """
    for user in serialize_user_data():
        if user['id'] == current_user_id:
            return user


@users_bp.route('/', methods=['GET'])
def users_list():
    """
    The route for displaying all users in the 'Users' Tab
    :return: renders the html template users.html
    """
    users = serialize_user_data()
    current_user_info = {}

    # checks if user is signed in.
    # If yes, then remove the data of the signed in user which is to be display it in a separate HTML panel
    if current_user.is_active:
        current_user_info = get_current_user_info(current_user.id)
        users.remove(current_user_info)
    else:
        flash('Sign in to start adding your favorite movies!')

    return render_template('users.html', users=users, signed_in_user=current_user_info)


@users_bp.route('/user_movies/<int:user_id>', methods=['GET'])
@login_required
def user_movies(user_id):
    """
    Route for rending a user's movies' posters in grids
    :param user_id: int
    :return: renders the user_movies.html template
    """
    user = data_manager.get_user_by_id(user_id)
    user_movies = data_manager.get_user_movies(user_id)
    return render_template('user_movies.html', user=user, user_movies=user_movies)


@users_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    Route to signup user into the app
    :return: renders user_signup.html or redirects users to users.signin
    """
    # If user is already signed in, redirect user to the Users page.
    if current_user.is_authenticated:
        return redirect(url_for('users.users_list'))

    # Handles Post request from the signup form
    form = SignupForm()
    if form.validate_on_submit():
        # Hash the user's password
        password_hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        # Create a new User instance
        user = User(
            name=form.display_name.data,
            username=form.username.data,
            email=form.email.data,
            password=password_hashed,
            date_registered=datetime.utcnow().strftime('%d-%b-%Y')
        )

        db.session.add(user)
        db.session.commit()

        # Send success message to user and redirect user to signin page
        flash('Your account has been created! You can now sign in.', 'success')
        return redirect(url_for('users.signin'))

    # if GET request, renders the signup form
    return render_template('user_signup.html', form=form)


@users_bp.route('/signin', methods=['GET', 'POST'])
def signin():
    """
    Route that signs in users into the app.
    :return: renders the user_signin.html template
    """
    # If user is already signed in, redirect user to the Users page.
    if current_user.is_authenticated:
        return redirect(url_for('users.users_list'))

    # Handles Post request from the signin form
    form = SigninForm()
    if form.validate_on_submit():
        user = data_manager.get_user_by_email(form.email.data)
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            flash('Click the `Account Tab` to add Movies', 'success')

            # redirects user the resource user was trying to access before signin or the users page
            next_page = request.args.get('next')
            return redirect(next_page or url_for('users.users_list'))
        else:
            flash('Error: Please check your email and password', 'error')

    # if GET request, renders the signin form
    return render_template('user_signin.html', form=form)


@users_bp.route('/logout')
def signout():
    """
    signout user from the app
    :return: redirect user to the home page
    """
    logout_user()
    return redirect(url_for('home.home'))


@users_bp.route('/delete_account/<int:user_id>', methods=['POST'])
def delete_account(user_id):
    """
    Route for deleting user account, given a user id
    :param user_id: int
    :return: redirects user to home page
    """
    # Logout the user
    logout_user()

    # Retrieve the user and delete it from the database
    user = data_manager.get_user_by_id(user_id)
    if user:
        # Delete user's associated movies using the  relationship
        db.session.delete(user)
        db.session.commit()
        flash('Your account and associated movies have been deleted.', 'success')
    else:
        flash('Error: User not found!', 'error')
        return redirect(url_for('users.users_list'))

    return redirect(url_for('home.home'))

movieweb_app/templates/index.html
{% extends "layout.html" %}

{% block form %}{% endblock form %}

{% block content %}
<!-- Home Page -->
   <header id="home">

      <div class="banner">
         <div class="banner-text">
            <h1>Movie App.</h1>
            <h3>
              Manage and keep track of your  <span>favourite movies.</span>
            </h3>
            <hr />
         </div>
          <div>
             <form action="/users/signup">
                <button class="submit">Get Started</button>
             </form>

         </div>
      </div>
   </header> <!-- Header End -->
{% endblock content %}

movieweb_app/templates/layout.html
<!DOCTYPE html>

<head>

   <!--- Basic Page Settings
   ================================================== -->
   <meta charset="utf-8">
	<title> Movieweb App</title>

   <!-- Mobile Specific Metas
   ================================================== -->
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

	<!-- CSS
    ================================================== -->
   <link rel="stylesheet" href="{{ url_for('static', filename='css/default.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/magnific-popup.css') }}">
   {% block CSS %}
	<link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
   {% endblock CSS %}

   <!-- FONT AWESOME
    ================================================== -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

</head>

<body>

<!-- Nav bar -->
      <nav id="nav-wrap">
          <ul id="nav" class="nav align-center">
              {% block home %}
              <li class="current"><a href="{{ url_for('home.home') }}">Home</a></li>
              {% endblock home %}

              {% block users %}
                <li><a  href="{{ url_for('users.users_list') }}">Users</a></li>
              {% endblock users %}

              {% if current_user.is_authenticated %}

                  {% block account %}
                   <li ><a href="{{ url_for('movies.add_movie', user_id=current_user.id) }}">Account</a></li>
                  {% endblock account %}

                  {% block signout %}
                  <li><a href="{{ url_for('users.signout') }}">Sign out</a></li>
                  {% endblock signout %}

              {% else %}

                  {% block signin %}
                  <li><a href="{{ url_for('users.signin') }}">Sign in</a></li>
                  {% endblock signin %}
              {% endif %}
          </ul>
      </nav> <!-- end nav-bar -->

   {% block content %}
<!--        other page's contents go in here-->
   {% endblock content %}

   <!-- Java Script
   ================================================== -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   <script src="{{ url_for('static', filename='js/jquery.fittext.js') }}"></script>
   <script src="{{ url_for('static', filename='js/jquery.magnific-popup.min.js') }}"></script>
   <script src="{{ url_for('static', filename='js/init.js') }}"></script>
</body>

</html>

movieweb_app/templates/messages.html
{% block form %}
<!-- Display Form Errors to users -->
    {% if form.errors %}
            <div class="message error">
            {% for field_name, errors in form.errors.items() %}
                    {% for error in errors %}
                        <span class="message error">{{ error }}</span>
                    {% endfor %}
            {% endfor %}
            </div>
    {% endif %}
{% endblock form %}

    <!-- Display Messages -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
                <div class="message">
                    {% for category, message in messages %}
                        <span class="message {{ category }}">{{ message }}</span>
                    {% endfor %}
                </div>
        {% endif %}
    {% endwith %}

movieweb_app/templates/movies_manager.html
{% extends "layout.html" %}

{% block CSS %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
{% endblock CSS %}

<!-- Nav bar -->
{% block home %}
<li><a href="{{ url_for('home.home') }}">Home</a></li>
{% endblock home %}

{% if current_user.is_authenticated %}
    {% block account %}
    <li class="current"><a href="{{ url_for('movies.add_movie', user_id=current_user.id) }}">Account</a></li>
    {% endblock account %}
{% endif %}
<!-- end Nav bar -->

{% block content %}
<section id="movies-manager">

    {% if current_user.is_authenticated %}
        <div class="account-links item-wrap">
            <a href="#" class=""><i class="fas fa-user fa-lg"></i> Update Profile
            </a>
            <a href="#{{ current_user.id }}" class=""><i class="fas fa-ban "></i> Delete Account
            </a>
        </div>

        <div class="row">
            <div class="seven row align-center">
                <div class="row align-center">
                    <h1><span>Movies Manager</span></h1>
                </div>

                <div class="row add-movie align-center">
                    <form action="{{ url_for('movies.add_movie', user_id=current_user.id) }}" method="POST">
                        <div>
                            <input type="text" placeholder="Enter Movie Name" name="movie_name">
                            <button type="submit">Add Movie</button>
                        </div>
                    </form>
                </div>

                <p>Click the eye icon to toggle Watched Status! </p>
                <p>Default is No.</p>

                <div class="row movie-list-wrapper">
                    <ul class="movie-list">
                        {% for movies in user_movies %}
                            {% if movies %}
                                <li class="add-bottom">
                                <span>{{ movies.title }}</span>
                                <div>
                                    <button type="submit">
                                        <a href="{{ url_for('movies.update_movie', user_id=current_user.id, movie_id=movies.id) }}" >
                                            <i class="fas fa-edit "></i>
                                        </a>
                                    </button>

                                    <button class="item-wrap">
                                        <a href="#{{ movies.id }}">
                                            <i class="fas fa-trash  "></i>
                                        </a>
                                    </button>
                                    <form
                                            action="" method="POST">
                                        <button type="submit">
                                            {% if movies.watched == 'Yes' %}
                                                <i class="fas fa-eye fa-lg"></i>
                                            {% else %}
                                                <i class="fas fa-eye-slash "></i>
                                            {% endif %}
                                        </button>
                                    </form>
                                </div>
                                <label>
                                    Already Watched Movie?:
                                    <span class="watched">{{ movies.watched }}</span>
                                </label>
                            </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                 {% for movies in user_movies %}
                    {% if movies %}
                        <!--     Delete Button modal               -->
                        <div id="{{ movies.id }}" class=" popup-modal mfp-hide">
                            <p>Are you sure you want to delete {{ movies.title }} ?</p>
                            <form
                                    action="{{ url_for('movies.delete_movie', user_id=current_user.id, movie_id=movies.id) }}"
                                  method="POST">
                                <button type="submit">
                                    Delete
                                </button>
                                <button class="popup-modal-dismiss">
                                    cancel
                                </button>
                            </form>
                        </div>
                    {% endif %}
                {% endfor %}

                <div id="{{ current_user.id }}" class=" popup-modal mfp-hide">
                    <p>Are you sure you want to delete your account?</p>
                    <form
                            action="{{ url_for('users.delete_account', user_id=current_user.id) }}"
                          method="POST">
                        <button type="submit">
                            Delete
                        </button>
                        <button class="popup-modal-dismiss">
                            cancel
                        </button>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
</section>
{% endblock content %}

movieweb_app/templates/update_movie.html
{% extends "layout.html" %}

{% block CSS %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
{% endblock CSS %}

<!-- Nav bar -->
{% block home %}
  <li ><a href="{{ url_for('home.home') }}">Home</a></li>
{% endblock home %}

{% block account %}
    <li class="current"><a href="{{ url_for('movies.add_movie', user_id=current_user.id) }}">Account</a></li>
{% endblock account %}
<!-- end Nav bar -->

{% block content %}
<section id="sign-up">

    <div class="row align-center">
        <p> UPDATE </p>
    </div>
    <div class="row">
        <div class="seven row align-center">
            <form action="{{ url_for('movies.update_movie', user_id=user_id, movie_id=user_movie.id) }}" method="POST"
                  class="align-center">

                <fieldset class="align-center">
                    <label for="movie_name">Title (Readonly) </label>
                    <input type="text" id="movie_name" name="movie_name" class="form-input" required readonly="readonly"
                           value="{{ user_movie.title }}">

                    <label for="movie_actors">Actors: </label>
                    <input type="text" id="movie_actors" name="movie_actors" class="form-input" required
                           value="{{ user_movie.actors }}">

                    <label for="movie_genre">Genre: </label>
                    <input type="text" id="movie_genre" name="movie_genre" class="form-input" required
                           value="{{ user_movie.genre }}">

                    <label for="movie_plot">Movie Plot: </label>
                    <textarea id="movie_plot" name="movie_plot" class="form-input" required
                              rows="5"> {{ user_movie.plot }} </textarea>

                    <div>
                        <button type="submit" class="">Update</button>
                    </div>
                </fieldset>
            </form>

        </div>

    </div>

</section>
{% endblock content %}

movieweb_app/templates/user_signin.html
{% extends "index.html" %}

{% block CSS %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
{% endblock CSS %}

<!-- Nav bar -->
{% block home %}
  <li ><a href="{{ url_for('home.home') }}">Home</a></li>
{% endblock home %}

{% block signin %}
<li class="current"><a href="{{ url_for('users.signin') }}">Sign in</a></li>
{% endblock signin %}
<!-- end Nav bar -->

{% block content %}
<section id="sign-in">

    {% include "messages.html" %}

    <div class="row align-center">
        <p> SiGN-IN</p>
    </div>
    <div class="row">
        <div class="seven row align-center">
            <form action="{{ url_for('users.signin') }}" method="POST" class="align-center">
                {{ form.hidden_tag() }}
                <fieldset class="align-center">
                    {{ form.email(class="form-input", placeholder=" Enter your email")}}
                    {% for error in form.email.errors %}
                        <span class="form-error">{{ error }}</span>
                    {% endfor %}

                    {{ form.password(class="form-input", placeholder=" Type your password")}}
                    {% for error in form.password.errors %}
                        <span class="form-error">{{ error }}</span>
                    {% endfor %}

                    <div>
                        <button type="submit" class="signup-button">{{ form.submit.label.text }}</button>
                    </div>
                    <div id="message-success">
                        <a href="{{ url_for('users.signup') }}" class="signup-ref-link">Sign up</a>
                        <a href="">Forgot Password ?</a><br>
                    </div>
                </fieldset>
            </form>


        </div>

    </div>

</section>
{% endblock content %}

movieweb_app/templates/user_signup.html
{% extends "index.html" %}

{% block CSS %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/layout.css') }}">
{% endblock CSS %}

<!-- Nav bar -->
{% block home %}
  <li ><a href="{{ url_for('home.home') }}">Home</a></li>
{% endblock home %}

{% block signup %}
<li class="current"><a href="{{ url_for('users.signup') }}">Sign up</a></li>
{% endblock signup %}
<!-- end Nav bar -->

{% block content %}
<section id="sign-up">

     {% include "messages.html" %}

    <div class="row align-center">
        <p> SiGN-UP</p>
    </div>
    <div class="row">
        <div class="seven row align-center">
            <form action="{{ url_for('users.signup') }}" method="POST"  class="align-center">
                 {{ form.hidden_tag() }}

                <fieldset class="align-center">
                    {{ form.display_name(class="form-input", placeholder=" Enter your display name")}}

                    {{ form.username(class="form-input", placeholder=" Enter your username")}}

                    {{ form.email(class="form-input", placeholder=" Enter your email")}}

                    {{ form.password(class="form-input", placeholder=" Type your password")}}

                    {{ form.confirm_password(class="form-input", placeholder=" Confirm password")}}

                    <div>
                        <button type="submit" class="signup-button">{{ form.submit.label.text }}</button>
                    </div>
                </fieldset>
            </form>
        </div>

    </div>

</section>
{% endblock content %}